-- Seed core technology entities and aliases.
-- Safe to run repeatedly (idempotent upsert).

WITH seed_entities(canonical_name, entity_type, wikidata_id, source, confidence) AS (
    VALUES
        ('OpenAI', 'company', 'Q21708200', 'manual', 1.000),
        ('Anthropic', 'company', 'Q115813237', 'manual', 1.000),
        ('Google', 'company', 'Q95', 'manual', 1.000),
        ('DeepMind', 'company', 'Q15733006', 'manual', 1.000),
        ('Microsoft', 'company', 'Q2283', 'manual', 1.000),
        ('Meta', 'company', 'Q380', 'manual', 1.000),
        ('Amazon', 'company', 'Q3884', 'manual', 1.000),
        ('Apple', 'company', 'Q312', 'manual', 1.000),
        ('NVIDIA', 'company', 'Q182477', 'manual', 1.000),
        ('TSMC', 'company', 'Q713318', 'manual', 1.000),
        ('Intel', 'company', 'Q248', 'manual', 1.000),
        ('AMD', 'company', 'Q128896', 'manual', 1.000),
        ('Cloudflare', 'company', 'Q4778915', 'manual', 1.000),
        ('Palo Alto Networks', 'company', 'Q7122302', 'manual', 1.000),
        ('CrowdStrike', 'company', 'Q5194310', 'manual', 1.000),
        ('Cisco', 'company', 'Q173395', 'manual', 1.000),
        ('ChatGPT', 'product', 'Q115564437', 'manual', 1.000),
        ('Claude', 'model', NULL, 'manual', 0.950),
        ('Gemini', 'model', NULL, 'manual', 0.950),
        ('Llama', 'model', NULL, 'manual', 0.950),
        ('DeepSeek', 'model', NULL, 'manual', 0.950),
        ('Grok', 'model', NULL, 'manual', 0.900),
        ('Copilot', 'product', NULL, 'manual', 0.900),
        ('CUDA', 'product', 'Q842398', 'manual', 1.000),
        ('Blackwell', 'chip', NULL, 'manual', 0.950),
        ('H100', 'chip', NULL, 'manual', 0.950),
        ('B200', 'chip', NULL, 'manual', 0.950),
        ('AI safety', 'topic', NULL, 'manual', 0.900),
        ('AI agents', 'topic', NULL, 'manual', 0.900),
        ('Semiconductors', 'topic', NULL, 'manual', 0.900),
        ('Alphabet', 'company', 'Q20800404', 'manual', 0.950),
        ('xAI', 'company', NULL, 'manual', 0.950),
        ('Mistral AI', 'company', NULL, 'manual', 0.950),
        ('Perplexity', 'company', NULL, 'manual', 0.900),
        ('Cohere', 'company', NULL, 'manual', 0.900),
        ('Hugging Face', 'company', NULL, 'manual', 0.950),
        ('Oracle', 'company', 'Q19900', 'manual', 0.950),
        ('IBM', 'company', 'Q37156', 'manual', 0.950),
        ('Salesforce', 'company', 'Q941127', 'manual', 0.950),
        ('Databricks', 'company', NULL, 'manual', 0.950),
        ('Snowflake', 'company', NULL, 'manual', 0.900),
        ('Arm Holdings', 'company', 'Q822477', 'manual', 0.950),
        ('ASML', 'company', 'Q155115', 'manual', 0.950),
        ('Qualcomm', 'company', 'Q544847', 'manual', 0.950),
        ('Broadcom', 'company', 'Q704718', 'manual', 0.950),
        ('Samsung Electronics', 'company', 'Q20718', 'manual', 0.950),
        ('SK hynix', 'company', 'Q483839', 'manual', 0.950),
        ('Micron', 'company', 'Q485499', 'manual', 0.950),
        ('Dell Technologies', 'company', 'Q2722041', 'manual', 0.900),
        ('HPE', 'company', 'Q19923099', 'manual', 0.900),
        ('Supermicro', 'company', NULL, 'manual', 0.900),
        ('Google Cloud', 'platform', NULL, 'manual', 0.950),
        ('Vertex AI', 'platform', NULL, 'manual', 0.950),
        ('Azure', 'platform', NULL, 'manual', 0.950),
        ('Azure AI', 'platform', NULL, 'manual', 0.950),
        ('AWS Bedrock', 'platform', NULL, 'manual', 0.950),
        ('Amazon SageMaker', 'platform', NULL, 'manual', 0.900),
        ('GitHub', 'platform', 'Q364', 'manual', 0.950),
        ('GitHub Copilot', 'product', NULL, 'manual', 0.950),
        ('GPT', 'model', NULL, 'manual', 0.900),
        ('GPT-4o', 'model', NULL, 'manual', 0.900),
        ('Claude Haiku', 'model', NULL, 'manual', 0.900),
        ('Gemini Flash', 'model', NULL, 'manual', 0.900),
        ('Llama 3', 'model', NULL, 'manual', 0.900),
        ('Llama 4', 'model', NULL, 'manual', 0.850),
        ('GB200', 'chip', NULL, 'manual', 0.950),
        ('H200', 'chip', NULL, 'manual', 0.950),
        ('TPU', 'chip', NULL, 'manual', 0.900),
        ('Trainium', 'chip', NULL, 'manual', 0.900),
        ('Inferentia', 'chip', NULL, 'manual', 0.900),
        ('MI300', 'chip', NULL, 'manual', 0.900),
        ('MI350', 'chip', NULL, 'manual', 0.850),
        ('EPYC', 'chip', NULL, 'manual', 0.900),
        ('Xeon', 'chip', NULL, 'manual', 0.900),
        ('Gaudi', 'chip', NULL, 'manual', 0.850),
        ('AI infrastructure', 'topic', NULL, 'manual', 0.900),
        ('AI inference', 'topic', NULL, 'manual', 0.900),
        ('AI training', 'topic', NULL, 'manual', 0.900),
        ('Cybersecurity', 'topic', NULL, 'manual', 0.900),
        ('Ransomware', 'topic', NULL, 'manual', 0.900),
        ('Open-source AI', 'topic', NULL, 'manual', 0.900),
        ('Robotics', 'topic', NULL, 'manual', 0.850),
        ('Data center', 'topic', NULL, 'manual', 0.900),
        ('Semiconductor equipment', 'topic', NULL, 'manual', 0.900)
),
upsert_entities AS (
    INSERT INTO public.entity_registry (
        canonical_name,
        entity_type,
        wikidata_id,
        source,
        confidence,
        is_active,
        updated_at
    )
    SELECT canonical_name, entity_type, wikidata_id, source, confidence, TRUE, NOW()
    FROM seed_entities
    ON CONFLICT (canonical_name) DO UPDATE
    SET entity_type = EXCLUDED.entity_type,
        wikidata_id = COALESCE(EXCLUDED.wikidata_id, public.entity_registry.wikidata_id),
        source = EXCLUDED.source,
        confidence = GREATEST(public.entity_registry.confidence, EXCLUDED.confidence),
        is_active = TRUE,
        updated_at = NOW()
    RETURNING entity_id, canonical_name
),
all_entities AS (
    SELECT entity_id, canonical_name
    FROM upsert_entities
    UNION
    SELECT er.entity_id, er.canonical_name
    FROM public.entity_registry er
    JOIN seed_entities se ON se.canonical_name = er.canonical_name
),
seed_aliases(canonical_name, alias, language, alias_type, weight, is_exact) AS (
    VALUES
        ('OpenAI', 'OpenAI', 'en', 'official', 1.000, TRUE),
        ('OpenAI', 'ChatGPT maker', 'en', 'generated', 0.700, TRUE),
        ('OpenAI', '开放人工智能', 'zh', 'translated', 0.800, TRUE),
        ('Anthropic', 'Anthropic', 'en', 'official', 1.000, TRUE),
        ('Anthropic', 'Claude maker', 'en', 'generated', 0.700, TRUE),
        ('Google', 'Google', 'en', 'official', 1.000, TRUE),
        ('Google', 'Google AI', 'en', 'product_family', 0.900, TRUE),
        ('Google', '谷歌', 'zh', 'translated', 1.000, TRUE),
        ('DeepMind', 'DeepMind', 'en', 'official', 1.000, TRUE),
        ('DeepMind', 'Google DeepMind', 'en', 'official', 1.000, TRUE),
        ('Microsoft', 'Microsoft', 'en', 'official', 1.000, TRUE),
        ('Microsoft', 'MSFT', 'en', 'ticker', 0.800, TRUE),
        ('Microsoft', '微软', 'zh', 'translated', 1.000, TRUE),
        ('Meta', 'Meta', 'en', 'official', 0.900, TRUE),
        ('Meta', 'Meta AI', 'en', 'product_family', 0.900, TRUE),
        ('Meta', 'Facebook parent', 'en', 'generated', 0.650, TRUE),
        ('Amazon', 'Amazon', 'en', 'official', 0.900, TRUE),
        ('Amazon', 'AWS', 'en', 'product_family', 0.950, TRUE),
        ('Amazon', 'Amazon Web Services', 'en', 'product_family', 0.950, TRUE),
        ('Apple', 'Apple', 'en', 'official', 0.900, TRUE),
        ('Apple', 'Apple Intelligence', 'en', 'product_family', 0.950, TRUE),
        ('Apple', 'AAPL', 'en', 'ticker', 0.800, TRUE),
        ('NVIDIA', 'NVIDIA', 'en', 'official', 1.000, TRUE),
        ('NVIDIA', 'NVDA', 'en', 'ticker', 0.900, TRUE),
        ('NVIDIA', '英伟达', 'zh', 'translated', 1.000, TRUE),
        ('TSMC', 'TSMC', 'en', 'official', 1.000, TRUE),
        ('TSMC', 'Taiwan Semiconductor Manufacturing Company', 'en', 'official', 0.950, TRUE),
        ('TSMC', '台积电', 'zh', 'translated', 1.000, TRUE),
        ('Intel', 'Intel', 'en', 'official', 1.000, TRUE),
        ('Intel', '英特尔', 'zh', 'translated', 1.000, TRUE),
        ('AMD', 'AMD', 'en', 'official', 1.000, TRUE),
        ('AMD', 'Advanced Micro Devices', 'en', 'official', 0.950, TRUE),
        ('Cloudflare', 'Cloudflare', 'en', 'official', 1.000, TRUE),
        ('Palo Alto Networks', 'Palo Alto Networks', 'en', 'official', 1.000, TRUE),
        ('Palo Alto Networks', 'PANW', 'en', 'ticker', 0.800, TRUE),
        ('CrowdStrike', 'CrowdStrike', 'en', 'official', 1.000, TRUE),
        ('CrowdStrike', 'CRWD', 'en', 'ticker', 0.800, TRUE),
        ('Cisco', 'Cisco', 'en', 'official', 1.000, TRUE),
        ('ChatGPT', 'ChatGPT', 'en', 'official', 1.000, TRUE),
        ('ChatGPT', 'GPT chatbot', 'en', 'generated', 0.700, TRUE),
        ('Claude', 'Claude', 'en', 'official', 0.900, TRUE),
        ('Claude', 'Claude Opus', 'en', 'model_variant', 0.900, TRUE),
        ('Claude', 'Claude Sonnet', 'en', 'model_variant', 0.900, TRUE),
        ('Gemini', 'Gemini', 'en', 'official', 0.900, TRUE),
        ('Gemini', 'Gemini Pro', 'en', 'model_variant', 0.900, TRUE),
        ('Gemini', 'Gemini Ultra', 'en', 'model_variant', 0.850, TRUE),
        ('Llama', 'Llama', 'en', 'official', 0.900, TRUE),
        ('Llama', 'Meta Llama', 'en', 'official', 0.950, TRUE),
        ('DeepSeek', 'DeepSeek', 'en', 'official', 0.950, TRUE),
        ('DeepSeek', 'DeepSeek R1', 'en', 'model_variant', 0.900, TRUE),
        ('Grok', 'Grok', 'en', 'official', 0.850, TRUE),
        ('Copilot', 'Copilot', 'en', 'official', 0.850, TRUE),
        ('Copilot', 'Microsoft Copilot', 'en', 'official', 0.950, TRUE),
        ('CUDA', 'CUDA', 'en', 'official', 1.000, TRUE),
        ('Blackwell', 'Blackwell', 'en', 'official', 0.950, TRUE),
        ('Blackwell', 'NVIDIA Blackwell', 'en', 'official', 1.000, TRUE),
        ('H100', 'H100', 'en', 'chip_name', 0.950, TRUE),
        ('B200', 'B200', 'en', 'chip_name', 0.950, TRUE),
        ('AI safety', 'AI safety', 'en', 'topic', 0.900, TRUE),
        ('AI safety', 'AI alignment', 'en', 'topic', 0.850, TRUE),
        ('AI agents', 'AI agents', 'en', 'topic', 0.900, TRUE),
        ('AI agents', 'agentic AI', 'en', 'topic', 0.850, TRUE),
        ('Semiconductors', 'semiconductors', 'en', 'topic', 0.900, TRUE),
        ('Semiconductors', 'chips', 'en', 'topic', 0.700, TRUE),
        ('Alphabet', 'Alphabet', 'en', 'official', 0.950, TRUE),
        ('Alphabet', 'Alphabet Inc.', 'en', 'official', 0.950, TRUE),
        ('Alphabet', 'Google parent', 'en', 'generated', 0.700, TRUE),
        ('Alphabet', 'GOOGL', 'en', 'ticker', 0.750, TRUE),
        ('Alphabet', 'GOOG', 'en', 'ticker', 0.750, TRUE),
        ('xAI', 'xAI', 'en', 'official', 0.950, TRUE),
        ('xAI', 'X.AI', 'en', 'official', 0.850, TRUE),
        ('Mistral AI', 'Mistral AI', 'en', 'official', 0.950, TRUE),
        ('Mistral AI', 'Mistral', 'en', 'official', 0.750, TRUE),
        ('Perplexity', 'Perplexity', 'en', 'official', 0.850, TRUE),
        ('Perplexity', 'Perplexity AI', 'en', 'official', 0.950, TRUE),
        ('Cohere', 'Cohere', 'en', 'official', 0.900, TRUE),
        ('Hugging Face', 'Hugging Face', 'en', 'official', 1.000, TRUE),
        ('Hugging Face', 'HuggingFace', 'en', 'official', 0.900, TRUE),
        ('Oracle', 'Oracle', 'en', 'official', 0.950, TRUE),
        ('Oracle', 'ORCL', 'en', 'ticker', 0.750, TRUE),
        ('Oracle', '甲骨文', 'zh', 'translated', 0.900, TRUE),
        ('IBM', 'IBM', 'en', 'official', 0.950, TRUE),
        ('IBM', 'International Business Machines', 'en', 'official', 0.900, TRUE),
        ('Salesforce', 'Salesforce', 'en', 'official', 0.950, TRUE),
        ('Salesforce', 'CRM', 'en', 'ticker', 0.650, TRUE),
        ('Salesforce', '赛富时', 'zh', 'translated', 0.850, TRUE),
        ('Databricks', 'Databricks', 'en', 'official', 0.950, TRUE),
        ('Snowflake', 'Snowflake', 'en', 'official', 0.750, TRUE),
        ('Snowflake', 'Snowflake AI', 'en', 'product_family', 0.750, TRUE),
        ('Arm Holdings', 'Arm Holdings', 'en', 'official', 0.950, TRUE),
        ('Arm Holdings', 'Arm Neoverse', 'en', 'product_family', 0.850, TRUE),
        ('ASML', 'ASML', 'en', 'official', 0.950, TRUE),
        ('ASML', '阿斯麦', 'zh', 'translated', 0.900, TRUE),
        ('Qualcomm', 'Qualcomm', 'en', 'official', 0.950, TRUE),
        ('Qualcomm', 'QCOM', 'en', 'ticker', 0.750, TRUE),
        ('Qualcomm', '高通', 'zh', 'translated', 0.900, TRUE),
        ('Broadcom', 'Broadcom', 'en', 'official', 0.950, TRUE),
        ('Broadcom', 'AVGO', 'en', 'ticker', 0.750, TRUE),
        ('Broadcom', '博通', 'zh', 'translated', 0.900, TRUE),
        ('Samsung Electronics', 'Samsung Electronics', 'en', 'official', 0.950, TRUE),
        ('Samsung Electronics', 'Samsung', 'en', 'official', 0.800, TRUE),
        ('Samsung Electronics', '三星', 'zh', 'translated', 0.900, TRUE),
        ('SK hynix', 'SK hynix', 'en', 'official', 0.950, TRUE),
        ('SK hynix', '海力士', 'zh', 'translated', 0.850, TRUE),
        ('Micron', 'Micron', 'en', 'official', 0.950, TRUE),
        ('Micron', 'Micron Technology', 'en', 'official', 0.950, TRUE),
        ('Micron', '美光', 'zh', 'translated', 0.850, TRUE),
        ('Dell Technologies', 'Dell Technologies', 'en', 'official', 0.950, TRUE),
        ('Dell Technologies', 'Dell', 'en', 'official', 0.850, TRUE),
        ('Dell Technologies', '戴尔', 'zh', 'translated', 0.850, TRUE),
        ('HPE', 'HPE', 'en', 'official', 0.900, TRUE),
        ('HPE', 'Hewlett Packard Enterprise', 'en', 'official', 0.950, TRUE),
        ('Supermicro', 'Supermicro', 'en', 'official', 0.900, TRUE),
        ('Supermicro', 'Super Micro', 'en', 'official', 0.850, TRUE),
        ('Google Cloud', 'Google Cloud', 'en', 'official', 0.950, TRUE),
        ('Google Cloud', 'GCP', 'en', 'product_family', 0.850, TRUE),
        ('Vertex AI', 'Vertex AI', 'en', 'official', 0.950, TRUE),
        ('Azure', 'Azure', 'en', 'official', 0.900, TRUE),
        ('Azure', 'Microsoft Azure', 'en', 'official', 0.950, TRUE),
        ('Azure AI', 'Azure AI', 'en', 'official', 0.950, TRUE),
        ('AWS Bedrock', 'AWS Bedrock', 'en', 'official', 0.950, TRUE),
        ('AWS Bedrock', 'Amazon Bedrock', 'en', 'official', 0.950, TRUE),
        ('Amazon SageMaker', 'Amazon SageMaker', 'en', 'official', 0.950, TRUE),
        ('Amazon SageMaker', 'SageMaker', 'en', 'official', 0.850, TRUE),
        ('GitHub', 'GitHub', 'en', 'official', 0.950, TRUE),
        ('GitHub Copilot', 'GitHub Copilot', 'en', 'official', 0.950, TRUE),
        ('GPT', 'GPT', 'en', 'official', 0.900, TRUE),
        ('GPT', 'GPT models', 'en', 'generated', 0.700, TRUE),
        ('GPT-4o', 'GPT-4o', 'en', 'official', 0.900, TRUE),
        ('GPT-4o', 'GPT 4o', 'en', 'generated', 0.800, TRUE),
        ('Claude Haiku', 'Claude Haiku', 'en', 'model_variant', 0.900, TRUE),
        ('Gemini Flash', 'Gemini Flash', 'en', 'model_variant', 0.900, TRUE),
        ('Llama 3', 'Llama 3', 'en', 'model_variant', 0.900, TRUE),
        ('Llama 4', 'Llama 4', 'en', 'model_variant', 0.850, TRUE),
        ('GB200', 'GB200', 'en', 'chip_name', 0.950, TRUE),
        ('GB200', 'NVIDIA GB200', 'en', 'chip_name', 0.950, TRUE),
        ('H200', 'H200', 'en', 'chip_name', 0.950, TRUE),
        ('TPU', 'TPU', 'en', 'chip_name', 0.900, TRUE),
        ('TPU', 'Google TPU', 'en', 'chip_name', 0.900, TRUE),
        ('Trainium', 'Trainium', 'en', 'chip_name', 0.900, TRUE),
        ('Trainium', 'AWS Trainium', 'en', 'chip_name', 0.900, TRUE),
        ('Inferentia', 'Inferentia', 'en', 'chip_name', 0.900, TRUE),
        ('Inferentia', 'AWS Inferentia', 'en', 'chip_name', 0.900, TRUE),
        ('MI300', 'MI300', 'en', 'chip_name', 0.900, TRUE),
        ('MI300', 'AMD MI300', 'en', 'chip_name', 0.900, TRUE),
        ('MI350', 'MI350', 'en', 'chip_name', 0.850, TRUE),
        ('EPYC', 'EPYC', 'en', 'chip_name', 0.900, TRUE),
        ('EPYC', 'AMD EPYC', 'en', 'chip_name', 0.900, TRUE),
        ('Xeon', 'Xeon', 'en', 'chip_name', 0.900, TRUE),
        ('Xeon', 'Intel Xeon', 'en', 'chip_name', 0.900, TRUE),
        ('Gaudi', 'Gaudi', 'en', 'chip_name', 0.750, TRUE),
        ('Gaudi', 'Intel Gaudi', 'en', 'chip_name', 0.900, TRUE),
        ('AI infrastructure', 'AI infrastructure', 'en', 'topic', 0.900, TRUE),
        ('AI infrastructure', 'AI infra', 'en', 'topic', 0.800, TRUE),
        ('AI inference', 'AI inference', 'en', 'topic', 0.900, TRUE),
        ('AI inference', 'inference serving', 'en', 'topic', 0.800, TRUE),
        ('AI training', 'AI training', 'en', 'topic', 0.900, TRUE),
        ('AI training', 'model training', 'en', 'topic', 0.750, TRUE),
        ('Cybersecurity', 'cybersecurity', 'en', 'topic', 0.900, TRUE),
        ('Cybersecurity', 'security breach', 'en', 'topic', 0.750, TRUE),
        ('Ransomware', 'ransomware', 'en', 'topic', 0.900, TRUE),
        ('Open-source AI', 'open-source AI', 'en', 'topic', 0.900, TRUE),
        ('Open-source AI', 'open source AI', 'en', 'topic', 0.850, TRUE),
        ('Robotics', 'robotics', 'en', 'topic', 0.850, TRUE),
        ('Data center', 'data center', 'en', 'topic', 0.900, TRUE),
        ('Data center', 'datacenter', 'en', 'topic', 0.850, TRUE),
        ('Semiconductor equipment', 'semiconductor equipment', 'en', 'topic', 0.900, TRUE),
        ('Semiconductor equipment', 'chipmaking equipment', 'en', 'topic', 0.800, TRUE)
),
deduped_aliases AS (
    SELECT DISTINCT ON (canonical_name, LOWER(alias))
        canonical_name,
        alias,
        language,
        alias_type,
        weight,
        is_exact
    FROM seed_aliases
    ORDER BY
        canonical_name,
        LOWER(alias),
        CASE WHEN alias = canonical_name THEN 0 ELSE 1 END,
        weight DESC,
        is_exact DESC,
        alias
)
INSERT INTO public.entity_alias (
    entity_id,
    alias,
    language,
    alias_type,
    weight,
    is_exact,
    is_active,
    updated_at
)
SELECT
    e.entity_id,
    a.alias,
    a.language,
    a.alias_type,
    a.weight,
    a.is_exact,
    TRUE,
    NOW()
FROM seed_aliases a
JOIN all_entities e ON e.canonical_name = a.canonical_name
WHERE NOT EXISTS (
    SELECT 1
    FROM public.entity_alias existing
    WHERE existing.entity_id = e.entity_id
      AND LOWER(existing.alias) = LOWER(a.alias)
)
ON CONFLICT (entity_id, LOWER(alias)) DO NOTHING;
